#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom4_DoAnWeb_CHDT.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CHDT")]
	public partial class MyDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblCTPNHAPKHO(tblCTPNHAPKHO instance);
    partial void UpdatetblCTPNHAPKHO(tblCTPNHAPKHO instance);
    partial void DeletetblCTPNHAPKHO(tblCTPNHAPKHO instance);
    partial void InserttblCTHD(tblCTHD instance);
    partial void UpdatetblCTHD(tblCTHD instance);
    partial void DeletetblCTHD(tblCTHD instance);
    partial void InserttblDIENTHOAI(tblDIENTHOAI instance);
    partial void UpdatetblDIENTHOAI(tblDIENTHOAI instance);
    partial void DeletetblDIENTHOAI(tblDIENTHOAI instance);
    partial void InserttblHOADON(tblHOADON instance);
    partial void UpdatetblHOADON(tblHOADON instance);
    partial void DeletetblHOADON(tblHOADON instance);
    partial void InserttblKHACHHANG(tblKHACHHANG instance);
    partial void UpdatetblKHACHHANG(tblKHACHHANG instance);
    partial void DeletetblKHACHHANG(tblKHACHHANG instance);
    partial void InserttblLOAIDIENTHOAI(tblLOAIDIENTHOAI instance);
    partial void UpdatetblLOAIDIENTHOAI(tblLOAIDIENTHOAI instance);
    partial void DeletetblLOAIDIENTHOAI(tblLOAIDIENTHOAI instance);
    partial void InserttblNHACUNGCAP(tblNHACUNGCAP instance);
    partial void UpdatetblNHACUNGCAP(tblNHACUNGCAP instance);
    partial void DeletetblNHACUNGCAP(tblNHACUNGCAP instance);
    partial void InserttblNHANVIEN(tblNHANVIEN instance);
    partial void UpdatetblNHANVIEN(tblNHANVIEN instance);
    partial void DeletetblNHANVIEN(tblNHANVIEN instance);
    partial void InserttblNHAPKHO(tblNHAPKHO instance);
    partial void UpdatetblNHAPKHO(tblNHAPKHO instance);
    partial void DeletetblNHAPKHO(tblNHAPKHO instance);
    partial void InserttblTAIKHOAN(tblTAIKHOAN instance);
    partial void UpdatetblTAIKHOAN(tblTAIKHOAN instance);
    partial void DeletetblTAIKHOAN(tblTAIKHOAN instance);
    #endregion
		
		public MyDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CHDTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCTPNHAPKHO> tblCTPNHAPKHOs
		{
			get
			{
				return this.GetTable<tblCTPNHAPKHO>();
			}
		}
		
		public System.Data.Linq.Table<tblCTHD> tblCTHDs
		{
			get
			{
				return this.GetTable<tblCTHD>();
			}
		}
		
		public System.Data.Linq.Table<tblDIENTHOAI> tblDIENTHOAIs
		{
			get
			{
				return this.GetTable<tblDIENTHOAI>();
			}
		}
		
		public System.Data.Linq.Table<tblHOADON> tblHOADONs
		{
			get
			{
				return this.GetTable<tblHOADON>();
			}
		}
		
		public System.Data.Linq.Table<tblKHACHHANG> tblKHACHHANGs
		{
			get
			{
				return this.GetTable<tblKHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<tblLOAIDIENTHOAI> tblLOAIDIENTHOAIs
		{
			get
			{
				return this.GetTable<tblLOAIDIENTHOAI>();
			}
		}
		
		public System.Data.Linq.Table<tblNHACUNGCAP> tblNHACUNGCAPs
		{
			get
			{
				return this.GetTable<tblNHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<tblNHANVIEN> tblNHANVIENs
		{
			get
			{
				return this.GetTable<tblNHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<tblNHAPKHO> tblNHAPKHOs
		{
			get
			{
				return this.GetTable<tblNHAPKHO>();
			}
		}
		
		public System.Data.Linq.Table<tblTAIKHOAN> tblTAIKHOANs
		{
			get
			{
				return this.GetTable<tblTAIKHOAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCTPNHAPKHO")]
	public partial class tblCTPNHAPKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPNK;
		
		private int _MADT;
		
		private int _SL;
		
		private System.Nullable<decimal> _GIANHAP;
		
		private EntityRef<tblDIENTHOAI> _tblDIENTHOAI;
		
		private EntityRef<tblNHAPKHO> _tblNHAPKHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPNKChanging(int value);
    partial void OnMAPNKChanged();
    partial void OnMADTChanging(int value);
    partial void OnMADTChanged();
    partial void OnSLChanging(int value);
    partial void OnSLChanged();
    partial void OnGIANHAPChanging(System.Nullable<decimal> value);
    partial void OnGIANHAPChanged();
    #endregion
		
		public tblCTPNHAPKHO()
		{
			this._tblDIENTHOAI = default(EntityRef<tblDIENTHOAI>);
			this._tblNHAPKHO = default(EntityRef<tblNHAPKHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPNK", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAPNK
		{
			get
			{
				return this._MAPNK;
			}
			set
			{
				if ((this._MAPNK != value))
				{
					if (this._tblNHAPKHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPNKChanging(value);
					this.SendPropertyChanging();
					this._MAPNK = value;
					this.SendPropertyChanged("MAPNK");
					this.OnMAPNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MADT
		{
			get
			{
				return this._MADT;
			}
			set
			{
				if ((this._MADT != value))
				{
					if (this._tblDIENTHOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADTChanging(value);
					this.SendPropertyChanging();
					this._MADT = value;
					this.SendPropertyChanged("MADT");
					this.OnMADTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public int SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIANHAP", DbType="Money")]
		public System.Nullable<decimal> GIANHAP
		{
			get
			{
				return this._GIANHAP;
			}
			set
			{
				if ((this._GIANHAP != value))
				{
					this.OnGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._GIANHAP = value;
					this.SendPropertyChanged("GIANHAP");
					this.OnGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDIENTHOAI_tblCTPNHAPKHO", Storage="_tblDIENTHOAI", ThisKey="MADT", OtherKey="MADT", IsForeignKey=true)]
		public tblDIENTHOAI tblDIENTHOAI
		{
			get
			{
				return this._tblDIENTHOAI.Entity;
			}
			set
			{
				tblDIENTHOAI previousValue = this._tblDIENTHOAI.Entity;
				if (((previousValue != value) 
							|| (this._tblDIENTHOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDIENTHOAI.Entity = null;
						previousValue.tblCTPNHAPKHOs.Remove(this);
					}
					this._tblDIENTHOAI.Entity = value;
					if ((value != null))
					{
						value.tblCTPNHAPKHOs.Add(this);
						this._MADT = value.MADT;
					}
					else
					{
						this._MADT = default(int);
					}
					this.SendPropertyChanged("tblDIENTHOAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHAPKHO_tblCTPNHAPKHO", Storage="_tblNHAPKHO", ThisKey="MAPNK", OtherKey="MAPNK", IsForeignKey=true)]
		public tblNHAPKHO tblNHAPKHO
		{
			get
			{
				return this._tblNHAPKHO.Entity;
			}
			set
			{
				tblNHAPKHO previousValue = this._tblNHAPKHO.Entity;
				if (((previousValue != value) 
							|| (this._tblNHAPKHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHAPKHO.Entity = null;
						previousValue.tblCTPNHAPKHOs.Remove(this);
					}
					this._tblNHAPKHO.Entity = value;
					if ((value != null))
					{
						value.tblCTPNHAPKHOs.Add(this);
						this._MAPNK = value.MAPNK;
					}
					else
					{
						this._MAPNK = default(int);
					}
					this.SendPropertyChanged("tblNHAPKHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCTHD")]
	public partial class tblCTHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHD;
		
		private int _MADT;
		
		private int _SLMUA;
		
		private System.Nullable<decimal> _GIABAN;
		
		private EntityRef<tblDIENTHOAI> _tblDIENTHOAI;
		
		private EntityRef<tblHOADON> _tblHOADON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDChanging(int value);
    partial void OnMAHDChanged();
    partial void OnMADTChanging(int value);
    partial void OnMADTChanged();
    partial void OnSLMUAChanging(int value);
    partial void OnSLMUAChanged();
    partial void OnGIABANChanging(System.Nullable<decimal> value);
    partial void OnGIABANChanged();
    #endregion
		
		public tblCTHD()
		{
			this._tblDIENTHOAI = default(EntityRef<tblDIENTHOAI>);
			this._tblHOADON = default(EntityRef<tblHOADON>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					if (this._tblHOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MADT
		{
			get
			{
				return this._MADT;
			}
			set
			{
				if ((this._MADT != value))
				{
					if (this._tblDIENTHOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADTChanging(value);
					this.SendPropertyChanging();
					this._MADT = value;
					this.SendPropertyChanged("MADT");
					this.OnMADTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLMUA", DbType="Int")]
		public int SLMUA
		{
			get
			{
				return this._SLMUA;
			}
			set
			{
				if ((this._SLMUA != value))
				{
					this.OnSLMUAChanging(value);
					this.SendPropertyChanging();
					this._SLMUA = value;
					this.SendPropertyChanged("SLMUA");
					this.OnSLMUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="Money")]
		public System.Nullable<decimal> GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDIENTHOAI_tblCTHD", Storage="_tblDIENTHOAI", ThisKey="MADT", OtherKey="MADT", IsForeignKey=true)]
		public tblDIENTHOAI tblDIENTHOAI
		{
			get
			{
				return this._tblDIENTHOAI.Entity;
			}
			set
			{
				tblDIENTHOAI previousValue = this._tblDIENTHOAI.Entity;
				if (((previousValue != value) 
							|| (this._tblDIENTHOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDIENTHOAI.Entity = null;
						previousValue.tblCTHDs.Remove(this);
					}
					this._tblDIENTHOAI.Entity = value;
					if ((value != null))
					{
						value.tblCTHDs.Add(this);
						this._MADT = value.MADT;
					}
					else
					{
						this._MADT = default(int);
					}
					this.SendPropertyChanged("tblDIENTHOAI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHOADON_tblCTHD", Storage="_tblHOADON", ThisKey="MAHD", OtherKey="MAHD", IsForeignKey=true)]
		public tblHOADON tblHOADON
		{
			get
			{
				return this._tblHOADON.Entity;
			}
			set
			{
				tblHOADON previousValue = this._tblHOADON.Entity;
				if (((previousValue != value) 
							|| (this._tblHOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHOADON.Entity = null;
						previousValue.tblCTHDs.Remove(this);
					}
					this._tblHOADON.Entity = value;
					if ((value != null))
					{
						value.tblCTHDs.Add(this);
						this._MAHD = value.MAHD;
					}
					else
					{
						this._MAHD = default(int);
					}
					this.SendPropertyChanged("tblHOADON");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDIENTHOAI")]
	public partial class tblDIENTHOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MADT;
		
		private string _TENDT;
		
		private string _HINH;
		
		private decimal _GIAMUA;
		
		private decimal _GIABAN;
		
		private string _MOTA;
		
		private int _MALOAI;
		
		private int _SLTON;
		
		private EntitySet<tblCTPNHAPKHO> _tblCTPNHAPKHOs;
		
		private EntitySet<tblCTHD> _tblCTHDs;
		
		private EntityRef<tblLOAIDIENTHOAI> _tblLOAIDIENTHOAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADTChanging(int value);
    partial void OnMADTChanged();
    partial void OnTENDTChanging(string value);
    partial void OnTENDTChanged();
    partial void OnHINHChanging(string value);
    partial void OnHINHChanged();
    partial void OnGIAMUAChanging(decimal value);
    partial void OnGIAMUAChanged();
    partial void OnGIABANChanging(decimal value);
    partial void OnGIABANChanged();
    partial void OnMOTAChanging(string value);
    partial void OnMOTAChanged();
    partial void OnMALOAIChanging(int value);
    partial void OnMALOAIChanged();
    partial void OnSLTONChanging(int value);
    partial void OnSLTONChanged();
    #endregion
		
		public tblDIENTHOAI()
		{
			this._tblCTPNHAPKHOs = new EntitySet<tblCTPNHAPKHO>(new Action<tblCTPNHAPKHO>(this.attach_tblCTPNHAPKHOs), new Action<tblCTPNHAPKHO>(this.detach_tblCTPNHAPKHOs));
			this._tblCTHDs = new EntitySet<tblCTHD>(new Action<tblCTHD>(this.attach_tblCTHDs), new Action<tblCTHD>(this.detach_tblCTHDs));
			this._tblLOAIDIENTHOAI = default(EntityRef<tblLOAIDIENTHOAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MADT
		{
			get
			{
				return this._MADT;
			}
			set
			{
				if ((this._MADT != value))
				{
					this.OnMADTChanging(value);
					this.SendPropertyChanging();
					this._MADT = value;
					this.SendPropertyChanged("MADT");
					this.OnMADTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDT", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENDT
		{
			get
			{
				return this._TENDT;
			}
			set
			{
				if ((this._TENDT != value))
				{
					this.OnTENDTChanging(value);
					this.SendPropertyChanging();
					this._TENDT = value;
					this.SendPropertyChanged("TENDT");
					this.OnTENDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAMUA", DbType="Money NOT NULL")]
		public decimal GIAMUA
		{
			get
			{
				return this._GIAMUA;
			}
			set
			{
				if ((this._GIAMUA != value))
				{
					this.OnGIAMUAChanging(value);
					this.SendPropertyChanging();
					this._GIAMUA = value;
					this.SendPropertyChanged("GIAMUA");
					this.OnGIAMUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="Money NOT NULL")]
		public decimal GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTA", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string MOTA
		{
			get
			{
				return this._MOTA;
			}
			set
			{
				if ((this._MOTA != value))
				{
					this.OnMOTAChanging(value);
					this.SendPropertyChanging();
					this._MOTA = value;
					this.SendPropertyChanged("MOTA");
					this.OnMOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Int NOT NULL")]
		public int MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if (this._tblLOAIDIENTHOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLTON", DbType="Int NOT NULL")]
		public int SLTON
		{
			get
			{
				return this._SLTON;
			}
			set
			{
				if ((this._SLTON != value))
				{
					this.OnSLTONChanging(value);
					this.SendPropertyChanging();
					this._SLTON = value;
					this.SendPropertyChanged("SLTON");
					this.OnSLTONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDIENTHOAI_tblCTPNHAPKHO", Storage="_tblCTPNHAPKHOs", ThisKey="MADT", OtherKey="MADT")]
		public EntitySet<tblCTPNHAPKHO> tblCTPNHAPKHOs
		{
			get
			{
				return this._tblCTPNHAPKHOs;
			}
			set
			{
				this._tblCTPNHAPKHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDIENTHOAI_tblCTHD", Storage="_tblCTHDs", ThisKey="MADT", OtherKey="MADT")]
		public EntitySet<tblCTHD> tblCTHDs
		{
			get
			{
				return this._tblCTHDs;
			}
			set
			{
				this._tblCTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLOAIDIENTHOAI_tblDIENTHOAI", Storage="_tblLOAIDIENTHOAI", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public tblLOAIDIENTHOAI tblLOAIDIENTHOAI
		{
			get
			{
				return this._tblLOAIDIENTHOAI.Entity;
			}
			set
			{
				tblLOAIDIENTHOAI previousValue = this._tblLOAIDIENTHOAI.Entity;
				if (((previousValue != value) 
							|| (this._tblLOAIDIENTHOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLOAIDIENTHOAI.Entity = null;
						previousValue.tblDIENTHOAIs.Remove(this);
					}
					this._tblLOAIDIENTHOAI.Entity = value;
					if ((value != null))
					{
						value.tblDIENTHOAIs.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(int);
					}
					this.SendPropertyChanged("tblLOAIDIENTHOAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCTPNHAPKHOs(tblCTPNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.tblDIENTHOAI = this;
		}
		
		private void detach_tblCTPNHAPKHOs(tblCTPNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.tblDIENTHOAI = null;
		}
		
		private void attach_tblCTHDs(tblCTHD entity)
		{
			this.SendPropertyChanging();
			entity.tblDIENTHOAI = this;
		}
		
		private void detach_tblCTHDs(tblCTHD entity)
		{
			this.SendPropertyChanging();
			entity.tblDIENTHOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHOADON")]
	public partial class tblHOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAHD;
		
		private System.DateTime _NGAYLAP;
		
		private System.Nullable<decimal> _TONGTG;
		
		private System.DateTime _HANBAOHANH;
		
		private System.Nullable<int> _MAKH;
		
		private System.Nullable<int> _MANV;
		
		private EntitySet<tblCTHD> _tblCTHDs;
		
		private EntityRef<tblKHACHHANG> _tblKHACHHANG;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDChanging(int value);
    partial void OnMAHDChanged();
    partial void OnNGAYLAPChanging(System.DateTime value);
    partial void OnNGAYLAPChanged();
    partial void OnTONGTGChanging(System.Nullable<decimal> value);
    partial void OnTONGTGChanged();
    partial void OnHANBAOHANHChanging(System.DateTime value);
    partial void OnHANBAOHANHChanged();
    partial void OnMAKHChanging(System.Nullable<int> value);
    partial void OnMAKHChanged();
    partial void OnMANVChanging(System.Nullable<int> value);
    partial void OnMANVChanged();
    #endregion
		
		public tblHOADON()
		{
			this._tblCTHDs = new EntitySet<tblCTHD>(new Action<tblCTHD>(this.attach_tblCTHDs), new Action<tblCTHD>(this.detach_tblCTHDs));
			this._tblKHACHHANG = default(EntityRef<tblKHACHHANG>);
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.DateTime NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTG", DbType="Money")]
		public System.Nullable<decimal> TONGTG
		{
			get
			{
				return this._TONGTG;
			}
			set
			{
				if ((this._TONGTG != value))
				{
					this.OnTONGTGChanging(value);
					this.SendPropertyChanging();
					this._TONGTG = value;
					this.SendPropertyChanged("TONGTG");
					this.OnTONGTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HANBAOHANH", DbType="Date")]
		public System.DateTime HANBAOHANH
		{
			get
			{
				return this._HANBAOHANH;
			}
			set
			{
				if ((this._HANBAOHANH != value))
				{
					this.OnHANBAOHANHChanging(value);
					this.SendPropertyChanging();
					this._HANBAOHANH = value;
					this.SendPropertyChanged("HANBAOHANH");
					this.OnHANBAOHANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Int")]
		public System.Nullable<int> MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._tblKHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int")]
		public System.Nullable<int> MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHOADON_tblCTHD", Storage="_tblCTHDs", ThisKey="MAHD", OtherKey="MAHD")]
		public EntitySet<tblCTHD> tblCTHDs
		{
			get
			{
				return this._tblCTHDs;
			}
			set
			{
				this._tblCTHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKHACHHANG_tblHOADON", Storage="_tblKHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public tblKHACHHANG tblKHACHHANG
		{
			get
			{
				return this._tblKHACHHANG.Entity;
			}
			set
			{
				tblKHACHHANG previousValue = this._tblKHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._tblKHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKHACHHANG.Entity = null;
						previousValue.tblHOADONs.Remove(this);
					}
					this._tblKHACHHANG.Entity = value;
					if ((value != null))
					{
						value.tblHOADONs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblKHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblHOADON", Storage="_tblNHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblHOADONs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblHOADONs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCTHDs(tblCTHD entity)
		{
			this.SendPropertyChanging();
			entity.tblHOADON = this;
		}
		
		private void detach_tblCTHDs(tblCTHD entity)
		{
			this.SendPropertyChanging();
			entity.tblHOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKHACHHANG")]
	public partial class tblKHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKH;
		
		private string _TENKH;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private string _EMAIL;
		
		private EntitySet<tblHOADON> _tblHOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(int value);
    partial void OnMAKHChanged();
    partial void OnTENKHChanging(string value);
    partial void OnTENKHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public tblKHACHHANG()
		{
			this._tblHOADONs = new EntitySet<tblHOADON>(new Action<tblHOADON>(this.attach_tblHOADONs), new Action<tblHOADON>(this.detach_tblHOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKH", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENKH
		{
			get
			{
				return this._TENKH;
			}
			set
			{
				if ((this._TENKH != value))
				{
					this.OnTENKHChanging(value);
					this.SendPropertyChanging();
					this._TENKH = value;
					this.SendPropertyChanged("TENKH");
					this.OnTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="VarChar(11)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(200)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKHACHHANG_tblHOADON", Storage="_tblHOADONs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<tblHOADON> tblHOADONs
		{
			get
			{
				return this._tblHOADONs;
			}
			set
			{
				this._tblHOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHOADONs(tblHOADON entity)
		{
			this.SendPropertyChanging();
			entity.tblKHACHHANG = this;
		}
		
		private void detach_tblHOADONs(tblHOADON entity)
		{
			this.SendPropertyChanging();
			entity.tblKHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLOAIDIENTHOAI")]
	public partial class tblLOAIDIENTHOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MALOAI;
		
		private string _TENLOAI;
		
		private EntitySet<tblDIENTHOAI> _tblDIENTHOAIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(int value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    #endregion
		
		public tblLOAIDIENTHOAI()
		{
			this._tblDIENTHOAIs = new EntitySet<tblDIENTHOAI>(new Action<tblDIENTHOAI>(this.attach_tblDIENTHOAIs), new Action<tblDIENTHOAI>(this.detach_tblDIENTHOAIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLOAIDIENTHOAI_tblDIENTHOAI", Storage="_tblDIENTHOAIs", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<tblDIENTHOAI> tblDIENTHOAIs
		{
			get
			{
				return this._tblDIENTHOAIs;
			}
			set
			{
				this._tblDIENTHOAIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblDIENTHOAIs(tblDIENTHOAI entity)
		{
			this.SendPropertyChanging();
			entity.tblLOAIDIENTHOAI = this;
		}
		
		private void detach_tblDIENTHOAIs(tblDIENTHOAI entity)
		{
			this.SendPropertyChanging();
			entity.tblLOAIDIENTHOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNHACUNGCAP")]
	public partial class tblNHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANCC;
		
		private string _TENNCC;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private string _EMAIL;
		
		private EntitySet<tblNHAPKHO> _tblNHAPKHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANCCChanging(int value);
    partial void OnMANCCChanged();
    partial void OnTENNCCChanging(string value);
    partial void OnTENNCCChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public tblNHACUNGCAP()
		{
			this._tblNHAPKHOs = new EntitySet<tblNHAPKHO>(new Action<tblNHAPKHO>(this.attach_tblNHAPKHOs), new Action<tblNHAPKHO>(this.detach_tblNHAPKHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNCC", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENNCC
		{
			get
			{
				return this._TENNCC;
			}
			set
			{
				if ((this._TENNCC != value))
				{
					this.OnTENNCCChanging(value);
					this.SendPropertyChanging();
					this._TENNCC = value;
					this.SendPropertyChanged("TENNCC");
					this.OnTENNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="NVarChar(11)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHACUNGCAP_tblNHAPKHO", Storage="_tblNHAPKHOs", ThisKey="MANCC", OtherKey="MANCC")]
		public EntitySet<tblNHAPKHO> tblNHAPKHOs
		{
			get
			{
				return this._tblNHAPKHOs;
			}
			set
			{
				this._tblNHAPKHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNHAPKHOs(tblNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.tblNHACUNGCAP = this;
		}
		
		private void detach_tblNHAPKHOs(tblNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.tblNHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNHANVIEN")]
	public partial class tblNHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANV;
		
		private string _TENNV;
		
		private string _DIACHI;
		
		private string _DIENTHOAI;
		
		private string _EMAIL;
		
		private EntitySet<tblHOADON> _tblHOADONs;
		
		private EntitySet<tblNHAPKHO> _tblNHAPKHOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(int value);
    partial void OnMANVChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnDIENTHOAIChanging(string value);
    partial void OnDIENTHOAIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public tblNHANVIEN()
		{
			this._tblHOADONs = new EntitySet<tblHOADON>(new Action<tblHOADON>(this.attach_tblHOADONs), new Action<tblHOADON>(this.detach_tblHOADONs));
			this._tblNHAPKHOs = new EntitySet<tblNHAPKHO>(new Action<tblNHAPKHO>(this.attach_tblNHAPKHOs), new Action<tblNHAPKHO>(this.detach_tblNHAPKHOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENTHOAI", DbType="VarChar(11)")]
		public string DIENTHOAI
		{
			get
			{
				return this._DIENTHOAI;
			}
			set
			{
				if ((this._DIENTHOAI != value))
				{
					this.OnDIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._DIENTHOAI = value;
					this.SendPropertyChanged("DIENTHOAI");
					this.OnDIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblHOADON", Storage="_tblHOADONs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<tblHOADON> tblHOADONs
		{
			get
			{
				return this._tblHOADONs;
			}
			set
			{
				this._tblHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblNHAPKHO", Storage="_tblNHAPKHOs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<tblNHAPKHO> tblNHAPKHOs
		{
			get
			{
				return this._tblNHAPKHOs;
			}
			set
			{
				this._tblNHAPKHOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHOADONs(tblHOADON entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblHOADONs(tblHOADON entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
		
		private void attach_tblNHAPKHOs(tblNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = this;
		}
		
		private void detach_tblNHAPKHOs(tblNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.tblNHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNHAPKHO")]
	public partial class tblNHAPKHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPNK;
		
		private System.Nullable<System.DateTime> _NGAYNHAP;
		
		private System.Nullable<decimal> _TONGTG;
		
		private System.Nullable<int> _MANV;
		
		private System.Nullable<int> _MANCC;
		
		private EntitySet<tblCTPNHAPKHO> _tblCTPNHAPKHOs;
		
		private EntityRef<tblNHACUNGCAP> _tblNHACUNGCAP;
		
		private EntityRef<tblNHANVIEN> _tblNHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPNKChanging(int value);
    partial void OnMAPNKChanged();
    partial void OnNGAYNHAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHAPChanged();
    partial void OnTONGTGChanging(System.Nullable<decimal> value);
    partial void OnTONGTGChanged();
    partial void OnMANVChanging(System.Nullable<int> value);
    partial void OnMANVChanged();
    partial void OnMANCCChanging(System.Nullable<int> value);
    partial void OnMANCCChanged();
    #endregion
		
		public tblNHAPKHO()
		{
			this._tblCTPNHAPKHOs = new EntitySet<tblCTPNHAPKHO>(new Action<tblCTPNHAPKHO>(this.attach_tblCTPNHAPKHOs), new Action<tblCTPNHAPKHO>(this.detach_tblCTPNHAPKHOs));
			this._tblNHACUNGCAP = default(EntityRef<tblNHACUNGCAP>);
			this._tblNHANVIEN = default(EntityRef<tblNHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPNK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPNK
		{
			get
			{
				return this._MAPNK;
			}
			set
			{
				if ((this._MAPNK != value))
				{
					this.OnMAPNKChanging(value);
					this.SendPropertyChanging();
					this._MAPNK = value;
					this.SendPropertyChanged("MAPNK");
					this.OnMAPNKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYNHAP
		{
			get
			{
				return this._NGAYNHAP;
			}
			set
			{
				if ((this._NGAYNHAP != value))
				{
					this.OnNGAYNHAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAP = value;
					this.SendPropertyChanged("NGAYNHAP");
					this.OnNGAYNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTG", DbType="Money")]
		public System.Nullable<decimal> TONGTG
		{
			get
			{
				return this._TONGTG;
			}
			set
			{
				if ((this._TONGTG != value))
				{
					this.OnTONGTGChanging(value);
					this.SendPropertyChanging();
					this._TONGTG = value;
					this.SendPropertyChanged("TONGTG");
					this.OnTONGTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Int")]
		public System.Nullable<int> MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._tblNHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="Int")]
		public System.Nullable<int> MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					if (this._tblNHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHAPKHO_tblCTPNHAPKHO", Storage="_tblCTPNHAPKHOs", ThisKey="MAPNK", OtherKey="MAPNK")]
		public EntitySet<tblCTPNHAPKHO> tblCTPNHAPKHOs
		{
			get
			{
				return this._tblCTPNHAPKHOs;
			}
			set
			{
				this._tblCTPNHAPKHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHACUNGCAP_tblNHAPKHO", Storage="_tblNHACUNGCAP", ThisKey="MANCC", OtherKey="MANCC", IsForeignKey=true)]
		public tblNHACUNGCAP tblNHACUNGCAP
		{
			get
			{
				return this._tblNHACUNGCAP.Entity;
			}
			set
			{
				tblNHACUNGCAP previousValue = this._tblNHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._tblNHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHACUNGCAP.Entity = null;
						previousValue.tblNHAPKHOs.Remove(this);
					}
					this._tblNHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.tblNHAPKHOs.Add(this);
						this._MANCC = value.MANCC;
					}
					else
					{
						this._MANCC = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblNHACUNGCAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNHANVIEN_tblNHAPKHO", Storage="_tblNHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public tblNHANVIEN tblNHANVIEN
		{
			get
			{
				return this._tblNHANVIEN.Entity;
			}
			set
			{
				tblNHANVIEN previousValue = this._tblNHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._tblNHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNHANVIEN.Entity = null;
						previousValue.tblNHAPKHOs.Remove(this);
					}
					this._tblNHANVIEN.Entity = value;
					if ((value != null))
					{
						value.tblNHAPKHOs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblNHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCTPNHAPKHOs(tblCTPNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.tblNHAPKHO = this;
		}
		
		private void detach_tblCTPNHAPKHOs(tblCTPNHAPKHO entity)
		{
			this.SendPropertyChanging();
			entity.tblNHAPKHO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTAIKHOAN")]
	public partial class tblTAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userID;
		
		private string _password;
		
		private string _role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public tblTAIKHOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(2)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
